---
title: " "
author: " "
output:
    html_document:
        theme: united
---

<br/>
<br/>

<b>
<font color="red" size=6>
Coloquio de investigación en desigualdad y ciudadanía - 2do Sem 2019
</b>
</font>
<br>


### Jueves 16:00  a 17:00, Semptiembre-Diciembre (online)

El objetivo de este coloquio es presentar trabajos en desarrollo que se encuentran temáticamente vinculados a áreas de desigualdad y/o ciudadanía, y que utilizan metodologías de análisis cuantitativo.

<br>


## Calendarización


| |  |  Presenta   | Tema |
|--|--|:--------|------------ |
| Septiembre  | 24 | -  | Calendarización sesiones
| Octubre     |  1 | Karen Tapia / Sebastian Cortínez  | Propuestas tema seminario
|             |  8 | Kevin Carrasco, Javiera Urrutia y Diego Esturillo  | Propuestas tema seminario
| Octubre     | 15 | Simón Varas  | Enfermedades Crónicas No Transmisibles y el efecto protector de la Cohesión Social en Chile
|             | 22 | Francisco Meneses | El rol del manejo del lenguaje en la transmisión intergeneracional de las habilidades políticas en jóvenes chilenos
|             |    | Martín Venegas | Propuestas tema seminario
|             | 29 | Carlos Budnevich  | La heterogeneidad de la composición social de las escuelas y su relación con el rendimiento académico en lenguaje y matemática de los estudiantes secundarios chilenos
| Noviembre   | 5  | Anaís Herrera | El rol de la familia y la escuela en la socialización política de las actitudes hacia la igualdad de derecho
|             | 12 | Matías Retamales | El efecto mitigador del sentido de justicia en la escuela sobre la intención de participación cívica: Un estudio multinivel sobre estudiantes chilenos
|             | 19 | - |
|             | 26 | semana de receso |
| Diciembre   |  3 | Sebastián Cortínez & Kevin Carrasco |
|             | 10 | Javiera Urrutia & Martín Henríquez |
|             | 17 | Diego Esturillo & Karen Tapia |



# Links

- [Del rigor en la ciencia](https://ciudadseva.com/texto/del-rigor-en-la-ciencia/)

- [Manterola & Otzen (2013) Porqué Investigar y Cómo Conducir una Investigación](https://scielo.conicyt.cl/scielo.php?script=sci_arttext&pid=S0717-95022013000400056)

- [Becker (2011) Manual de Escritura para Científicos Sociales](http://www.derechoshumanos.unlp.edu.ar/assets/files/documentos/manual-de-escritura-para-cientificos-sociales.pdf)

- [Good tips for academic writing from Kevin Lafferty](http://trophiccascades.forestry.oregonstate.edu/sites/trophic/files/Lafferty_WritingScientificPaper.pdf)

- [Publicación de artículos académicos: buenas prácticas y recomendaciones para la redacción y envío a revistas científicas](https://repositori.upf.edu/handle/10230/44599)

- [Formulación de una investigación cuantitativa (documento de presentación)](https://estrategias-ic.netlify.app/docpres/02_formu/02_formu.html#1).

- [Hernández et al El Planteamiento Cuantitativo del Problema](https://estrategias-ic.netlify.app/readings/cap3Hernandezetal2014.pdf)
