---
title: " "
author: " "
output:
    html_document:
        theme: united
---

<br/>
<br/>

<b>
<font color="red" size=6>
Coloquio de investigación en desigualdad y ciudadanía - 2do Sem 2019
</b>
</font>
<br>

### Miércoles 13:30  a 14:30, sala reuniones sur (334), edificio nuevo FACSO.


El objetivo de este coloquio es presentar trabajos en desarrollo que se encuentran temáticamente vinculados a áreas de desigualdad y/o ciudadanía, y que utilizan metodologías de análisis cuantitativo.

## Calendarización


| |  | Presenta   | Tema |
|--|--|:--|--|
| Agosto | 14 | -  | Calendarización sesiones
|  | 21 | Ronda presentaciones tesis | Francisco, Anaís, Simón
|  | 28 | Julio Iturra  | Estatus social subjetivo
| Septiembre   | 4 | José Conejeros  | Meritocracia
|   | 11  |   |   |
|   | 25  | Cristóbal Moya  | Encuesta factorial
| Octubre   | 2 | Catalina Miranda  | Ciudadanía y género
|   | 9  |  Daniel Miranda  | Formación ciudadana
|   | 16 |  Alejando Plaza y Guillermo Beck| Redes sociales e imágenes de la desigualdad
|   | 23  | Anaís Herrera |
|   | 30  | Francisco Meneses  |
|Noviembre  | 6  | Matías Montero & Simón Varas |
|   | 13  | Carlos Budnevich & Matías Retamal |
|   | 20  | José Conejeros - reloaded  |

# Congresos y conferencias

1.   [ISA FORUM OF SOCIOLOGY](https://www.isa-sociology.org/en/conferences/forum).
     - Fecha: 14 - 18 julio 2020
     - Lugar: Porto Alegre, Brasil.
     - Postulaciones: 30 septiembre 2019
2. [Congreso Interdisciplinario de Investigación en Educación - CIIE](http://ciie.cl/)
     - Fecha: 20, 21 y 22 de agosto, 2019
     - Lugar:
     - Postulaciones: Cerrado
3. [Congreso Internacional, ALAS 2019](https://www.alasperu2019.pe/)
    - Fecha: 1 a 6 diciembre, 2019
    - Lugar: Lima, Perú.
    - Postulaciones: Cerrado
4. [Conferencia CEDEUS-COES](https://cedeus-coes.cl/)  
     - Fecha:12 a 15 noviembre, 2019
     - Lugar: Santiago, Chile.
     - Postulaciones: Cerrado      
