---
title: " "
author: " "
output:
    html_document:
        theme: united
        highlight: tango
---

<br/>
<br/>

### PhD Sociology, Humboldt Universität <br/>
### Professor at [Institute of Sociology](http://www.sociologia.uc.cl), Pontificia Universidad Católica de Chile <br/>
### Deputy director [COES](http://www.coes.cl) - Centre for Social Conflict and Cohesion Studies

---

### _Latest publications_

<br/>
**Meritocracy and economic inequality: Perceptions, preferences and implications**.

  Castillo, JC. & Torres, A. , Atria, J & Maldonado, L. (2018)
Forthcoming in Revista Internacional de Sociología (ISI).

  The idea of meritocracy is related to the distribution of goods and rewards based on individual talent and effort, being a principle that legitimizes the unequal distribution of resources in modern societies. Despite the constant references to meritocracy in inequality and stratification research, there are still few conceptual and empirical attempts to understand to what extent individuals perceive and prefer meritocracy, as well as their consequences. The present research proposes a conceptual and empirical framework for  studying meritocratic perceptions and preferences, which is then related with economic inequality variables. Using data from the Chilean survey “Social justice and citizenship participation”, the analyses suggest that meritocratic perceptions and preferences are different constructs and that those perceiving an adequate functioning of meritocracy also perceive less economic inequality.


<br/>

**Poverty and wealth attributions: A second order confirmatory factor analysis model.**

  Castillo, JC & Rivera, M. (2018)
  Forthcoming in Psykhe (SCOPUS).

  The theory of attributions has a long tradition in studying explanations for the origin of poverty. Nevertheless, research regarding the perceived causes of wealth has been so far sidelined and not related to the study of poverty attributions. This paper focuses on the relationship between poverty and wealth attributions from a latent variable measurement perspective, for which it considers two basic attribution types: internal (based on individual behavior) and external (based on socio-structural determinants). The data comes from a 10-indicator scale from the national representative survey “Social Justice and Citizenship Participation”, applied in Chile in 2013 (N=1.245). Based in previous exploratory and confirmatory studies, a factorial confirmatory model for internal and external attributions of both poverty an wealth was estimated (four factors), based on which a second order two-factor confirmatory model was estimated, one for internal and one for external attributions, for both poverty and wealth. The results show for the first time evidence of common attributional dimensions for poverty and wealth

(see more in [Research](research.html))
