---
title: "Juan Carlos Castillo "
author: " "
output:
    html_document:
        theme: united
        toc: TRUE
        toc_float: TRUE
---

<br>
<br>

## Projects / Grants

<br>

- **Political socialization and citizenship education: The role of the family and the school** (2018 - 2021) FONDECYT Regular 1181239, associate researcher (principal researcher: Cristián Cox).


- **The moral economy of meritocracy and redistributive preference** (2016 - 2019) FONDECYT Regular 1160921, principal researcher. [(link to project website)](https://www.researchgate.net/project/The-moral-economy-of-meritocracy-and-redistributive-preferences)


- **Centre for Social Conflict and Cohesion Studies** [COES](www.coes.cl) (2013 - 2018 / 2019-2023) FONDAP CONICYT 15130009, principal researcher / deputy director.

<details>
<summary> *See more...* </summary>

- **Formación de Redes Internacionales entre Centros de Investigación, MIDE-IEA/DPC** (2013 - 2014) CONICYT DRI 130074, principal researcher.

- **Social justice and citizenship participation: An international comparison with focus on the case of Chile** (2012 - 2015) FONDECYT Iniciación 11121203, principal researcher.

- **Socialización política y experiencia escolar, Chile en contexto internacional** (2012 - 2015) FONDECYT Regular 1120630, associate researcher (principal researcher: Cristián Cox).

- **Inequality, social justice and political participation** (2011 - 2012) Inicio UC 11/2011, principal researcher.

- **Testing the stability of perception and justification of economic inequality in Chile: A cross-sectional time comparison** (2010 - 2011)	Inicio 24/2010, principal researcher.
</details>
<br>

## Papers

<br>

### Current paper projects

- Taking from the rich or giving to the poor: The two faces of support for redistribution (with Efraín García-Sánchez)

- Redistributive preferences in unequal contexts: Changes in Latin America between 2008 and 2014 (with Gonzalo Franetovic)

- Perceptions and Preferences about Meritocracy in International Comparison  [(*link to ISA 2018 presentation*)](https://juancarloscastillo.github.io/jc-castillo/documents/ISA2018presentation/castillo2018meritocracyISA.html#1)

- About the stability of meritocratic beliefs: A longitudinal measurement invariance approach (with Guillermo Beck)

- Income inequality and social cohesion. How objective and subjective income inequality affects generalized social trust in Latin American societies (with Sonja Zmerli).

- Equality or Insurance? The underlying motives for supporting social policy in Latin America (with Jose de Amesti - 1st author, Luis Maldonado & Jorge Atria). Submitted.

- Talent and Business Success: Economic elites&#39; moral economy of meritocracy in Chile (with Jorge Atria, Luis Maldonado & Simón Ramirez). Submitted.

- Medición de actitudes hacia la igualdad de derechos entre géneros en pruebas internacionales: Implicancias respecto a su validez (with Daniel Miranda & Angélica Bonilla).  Submitted - Preprint: <a href="https://osf.io/preprints/socarxiv/t87se/">
<i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>

- Do people perceive more inequality when more inequality exists? (with Martin Schröder). Revise & Resubmit.

<br>

### Peer-reviewed journal articles

(If you are looking for copies of my papers, check my site in [Researchgate](https://www.researchgate.net/profile/Juan_Castillo5/contributions)).

- Maldonado,L., Olivos, F. Azar, A. Castillo, J. & Atria, J.(2019) Risk exposure, humanitarianism and willingness to pay for universal healthcare: A cross-national analysis of 28 countries.  Accepted in _Social Justice Research_

- Cumsille, P., Martínez, L. Loyola, I. & Castillo, JC. (2018) Patterns of civic and political commitment in early adolescence. Forthcoming in _Journal of Early Adolescence_.

- Atria, J., Ramírez, S., Castillo, JC. & Maldonado, L. (2018) Studying meritocracy in an unequal context: Perspectives from chilean scholars. Forthcoming in Universum.

- Frei, R., Castillo, JC., Henríquez, R. & Suárez, J. (2018 - Forthcoming 2020) “¿Fruto del esfuerzo?”: los cambios en las atribuciones sobre pobreza y riqueza en Chile entre 1996 y 2015. _Latin American Research Review_.

- Castillo, JC. Olivos. F. & Azar, A. (2018) On the justice of pensions: A factorial survey approach. Accepted in _Social Science Quarterly_ [DOI: 10.1111/ssqu.12539](https://onlinelibrary.wiley.com/doi/abs/10.1111/ssqu.12539). <a href="https://www.researchgate.net/publication/328359653_Deserving_a_Just_Pension_A_Factorial_Survey_Approach">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a>

- Castillo, JC. & Torres, A. , Atria, J & Maldonado, L. (2018) Meritocracia y desigualdad económica: Percepciones, preferencias e implicancias. Forthcoming in Revista Internacional de Sociología (ISI).
<i class="ai ai-open-access fa-lg" style="font-size:20px"></i>
<a href="https://www.researchgate.net/publication/325225032_Meritocracia_y_desigualdad_economica_Percepciones_preferencias_e_implicancias_Meritocracy_and_Economic_inequality_Perceptions_preferences_and_implications">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a>
<a href="https://osf.io/preprints/socarxiv/qkpu4/">
<i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>

- Castillo, JC & Rivera,M. (2018) Poverty and wealth attributions: A second order confirmatory factor analysis model. Psykhe 27(2) 10.7764/psykhe.27.2.1152 (SCOPUS).
<a href="http://www.psykhe.cl/index.php/psykhe/article/view/1152/pdf_113"><i class="ai ai-open-access fa-lg" style="font-size:20px"></i>
<a href="https://www.researchgate.net/publication/326637297_Common_dimensions_for_poverty_and_wealth_attributions">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a>
<a href="https://osf.io/preprints/socarxiv/5xnrd/">
<i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>

- Atria, J., Amenábar, J., Sanchez, J., Castillo, JC & Cociña, M. (2017) Investigando a la élite económica: Lecciones y desafíos a partir del caso de Chile. Cultura, Hombre y Sociedad 27(2)5-36 (Scielo).
<i class="ai ai-open-access fa-lg" style="font-size:20px"></i>
<a href="https://www.researchgate.net/publication/322211841_Investigando_a_la_elite_economica_Lecciones_y_desafios_a_partir_del_caso_de_Chile_Researching_the_economic_elite_lessons_and_challenges_from_the_Chilean_case">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a>
[link to pdf](https://scielo.conicyt.cl/pdf/cuhso/v27n2/0719-2789-cuhso-27-02-00005.pdf)

- Miranda, D., Castillo, JC & Sandoval-Hernández, A. (2017) Young Citizens Participation: An empirical test of a conceptual model. _Youth & Society_ - online first (ISI).
<a href="https://www.researchgate.net/publication/320263594_Young_Citizens_Participation_Empirical_Testing_of_a_Conceptual_Model">
<i class="ai ai-researchgate fa-lg" style="font-size:20px;color:green"></i></a> [pdf]("documentos/papers/Miranda et al. 2017. Young Citizens Participation.pdf")

- Azar, A., Maldonado, L., Castillo, JC & Atria, J. (2018)
“Income, Egalitarianism, and Attitudes Towards Healthcare Policy: A Study on Public Attitudes in 29 Countries” _Public Health 148:59-69_ (ISI) [pdf]("documents/papers/azar et al 2017 income, egalitarianism and health redistribution.pdf")


<details>
<summary> *More...* </summary>

- Guerra, C. & Castillo, J (2016) Sintomatología en adolescentes victimizados sexualmente: El rol del apoyo de la familia y del grupo de pares. Revista sobre la infancia y la adolescencia, 11:66-80 (Latindex) [link](https://polipapers.upv.es/index.php/reinad/article/view/4478/6797)

- Castillo, J. (2016) Public opinion about just salaries in Chile: An exploratory study based on a factorial survey. Cuadernos ISUC 1(2)1:28 [link](http://sociologia.uc.cl/wp-content/uploads/2016/12/articulo-juan-carlos-castillo.pdf).

- Schneider, S. & Castillo, J. (2015) Poverty attributions and the perceived legitimacy of income inequalities: A comparison of East and West Germany. Social Psychology Quarterly 78(3):263-282 (ISI)[pdf]
("documents/papers/Schneider y Castillo - 2015 - Poverty Attributions and the Perceived Justice.pdf")

- Bascopé, M., Bonhomme, M., Cox, C., Castillo, JC., Miranda, D. (2015)  Curricular Guidelines and Citizenship Education in Latin American Schools. Revista Latinoamericana de Ciencias Sociales, Niñez & Juventud  13(2):1169-1190 (Scielo).[pdf](https://www.researchgate.net/publication/274250465_Citizenship_Education_in_Latin_America_Priorities_of_School_Curricula)

- Castillo, J. , Joignant, A., Palacios, D., & Tham, M. (2015)  Inequality, distributive justice and political participation. Bulletin of Latin American Research 34(4)486-50 (ISI) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i>
[pdf](documents/papers/Castilloetal2015InequalityJusticePoliticalPar.pdf)

- Zmerli, S. & Castillo, J. (2015)  Inequality and political trust. How objective and subjective inequality affects Latin American democracies. Social Science Research 52, 179-192 (ISI) [pdf](documents/papers/Zmerli & Castillo 2015 Inequality and political trust.pdf)

- Castillo, J., Cox, C., Miranda, D., Bascopé, M. & Bonhomme, M. (2014)  Mitigating the Political Participation Gap from the School: The Roles of Civic Knowledge and Classroom Climate. Journal of Youth Studies 18(1) 16-35. (ISI) [pdf](documents/papers/castillo et al 2014 mitigating the political participation gap _ final published.pdf)

- Castillo, J. (2014) Actitudes hacia el trabajo y justicia salarial en Chile. Temas de la Agenda Pública 66, 33-44 <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/269928176_Actitudes_hacia_el_trabajo_y_justicia_salarial_en_Chile)

- Castillo, J., Madero, I. & Miranda, D. (2014) Educación, desigualdad y creencias distributivas: Evidencia del caso chileno. Sociedad Hoy 24 13-31 (Latindex) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/264655431_Educacion_equidad_y_creencias_distributivas_Evidencias_del_caso_chileno)

- Castillo, J., Cox, C., Miranda, D. & Bascopé, M. & Bonhomme, M. (2014) Social inequality and changes in student's expected political participation in Chile. Education, citizenship & social justice 9(2) 140-156. (SCOPUS).[pdf](documents/papers/castillo2014studentspoliticalparticipation.pdf)

- Factor, R., Castillo, J. & Rattner, A (2014) Procedural justice, religiosity and minorities. Police Practice and Research 15(2)130-142 (SCOPUS)[link](https://www.tandfonline.com/doi/abs/10.1080/15614263.2013.874171)

- Preiss, D., Castillo, J., Flotts, P. & San Martin, E. (2013) Assessment of argumentative writing and critical thinking in higher education: Educational correlates and gender differences . Learning and Individual Differences 28, 193-203 (ISI)[link](https://www.researchgate.net/publication/259520367_Assessment_of_argumentative_writing_and_critical_thinking_in_higher_education_Educational_correlates_and_gender_differences)

- Preiss, D., Castillo, J., Grigorenko, H. & Manzi, J. (2013) Argumentative writing and academic achievement: A longitudinal study. Learning and Individual Differences 8,204-211 (ISI) [link](https://www.researchgate.net/publication/259520365_Argumentative_writing_and_academic_achievement_A_longitudinal_study)

- Castillo, J., Salamovich, A. & Madero, I. (2013) Clivajes partidarios y cambios en preferencias distributivas en Chile. Revista de Ciencia Política 33(2) 469-488 (ISI) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/257823109_Clivajes_partidarios_y_cambios_en_preferencias_distributivas_en_Chile)

- Castillo, J., Miranda, D. & Madero, I. (2013) Todos somos de clase media: Sobre el estatus social subjetivo en Chile. Latin American Research Review 48(1) 155-173 (ISI) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/236870281_Todos_somos_de_clase_media_Sobre_el_estatus_social_subjetivo_en_Chile)

- Castillo, J. (2013) Contrastes entre la desigualdad objetiva y subjetiva en Chile. Temas de la Agenda Pública 57, 1-15. (Latindex)<i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://politicaspublicas.uc.cl/wp-content/uploads/2015/02/serie-n-57-contrastes-entre-la-desigualdad-economica-objetiva-y-subjetiva-en-chile.pdf)

- Castillo, J. Leal. P. & Madero, I. & Miranda, D. (2012) ¿Son los chilenos igualmente solidarios? La influencia de los recursos personales en las donaciones de dinero. Opiniao Publica (SCOPUS) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://www.researchgate.net/publication/244484714_Son_los_chilenos_igualmente_solidarios_La_influencia_de_los_recursos_personales_en_las_donaciones_de_dinero).

- Castillo, J. (2012) La legitimidad de las desigualdades salariales. Una aproximación multidimensional. Revista Internacional de Sociología (ISI) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/viewFile/476/497)

- Madero, I. & Castillo , J. (2012) Sobre el estudio empírico de la solidaridad: Aproximaciones conceptuales y metodológicas. Polis.1(31) 391-409. (SCIELO) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [pdf](https://scielo.conicyt.cl/scielo.php?script=sci_arttext&pid=S0718-65682012000100021)

- Castillo, J., Miranda, D. & Carrasco, D. (2012) Percepción de desigualdad económica en Chile: Medición, diferencias y determinantes. Psykhé 21(1) 99-114. (SCOPUS) <i class="ai ai-open-access fa-lg" style="font-size:20px"></i>[pdf](https://scielo.conicyt.cl/pdf/psykhe/v21n1/art07.pdf)

- Castillo, J. (2012) Is inequality becoming just? Changes in public opinion about economic distribution in Chile. Bulletin of Latin American Research, 31(1)1-18. (ISI) [pdf](documentos/papers/castillo 2012 is inequality becoming just - BLAR.pdf)

- Castillo, J. (2011) Legitimacy of inequality in a highly unequal context: evidence from the Chilean case. _Social Justice Research_ 24 (4) 314-340.(ISI) [pdf]("documentos/papers/castillo 2011 legitimacy of inequality in a highly unequal context.pdf")

- Castillo, J. (2009). ¿Cuál es la Brecha Salarial Justa? Opinión Pública y Legitimación de la Desigualdad Económica en Chile. Estudios Públicos (113), 237-266.[link](https://www.cepchile.cl/cual-es-la-brecha-salarial-justa-opinion-publica-y-legitimacion-de-la/cep/2016-03-04/094825.html)

</details>

<br/>

### Books, chapters & working papers

- Breznau, N., Rinke, E., Wuttke, A., Adem, M., Adriaans, J., Alvarez-Benjumea, A., … Castillo, JC. … Żółtak, T. (2019, January 26). The Crowdsourced Replication Initiative: Investigating Immigration and Social Policy Preferences. Executive Report. https://doi.org/10.31235/osf.io/6j9qb. <a href="https://doi.org/10.31235/osf.io/6j9qb"><i class="ai ai-osf fa-lg" style="font-size:20px;color:blue"></i></a>

- Miranda, D. & Castillo, JC (2018) Measurement Model and Invariance Testing of Scales Measuring Egalitarian Values in ICCS 2009. In A. Sandoval-Hernandez, M. Isaac & D. Miranda (Eds.) Teaching tolerance in a globalized world. New York, NY: Springer Berlin Heidelberg. <i class="ai ai-open-access fa-lg" style="font-size:20px"></i>[Open Access](https://link.springer.com/chapter/10.1007/978-3-319-78692-6_3)

- Miranda, D., Castillo, JC. & Cumsille, P. (2018) The Political Socialization of Attitudes Toward Equal Rights from a Comparative Perspective . In A. Sandoval-Hernandez, M. Isaac & D. Miranda (Eds.) Teaching tolerance in a globalized world. New York, NY: Springer Berlin Heidelberg.<i class="ai ai-open-access fa-lg" style="font-size:20px"></i> [Open Access](https://link.springer.com/chapter/10.1007/978-3-319-78692-6_7)

- Bargsted, M., Castillo, J. & Somma, N. (2017) Political trust in Latin America. forthcoming in The Handbook of Political Trust (Zmerli, S. & Van der Meer, T.). In Press.

- Olivos, F., Mackenna, B., Castillo, JC, & Bargsted, M. (2015) Percepción de conflicto en Chile: Un análisis desde la opinión pública 2006-2013 (273-298).En: Castillo, M. & Maldonado, C. Desigualdades: Tolerancia, legitimación y conflicto en las sociedades latinoamericanas. Santiago: RIL [pdf]("documentos/papers/olivos, mackenna, castillo & bargsted 2015 percepcion de conflicto en chile.pdf").

- Cox, C. & Castillo, J (Eds.) (2015)  Aprendizaje de la ciudadanía: Contextos, experiencias y resultados. Santiago: Ediciones UC.

<details>

<summary> *See more...* </summary>

- Miranda, D. Castillo, J. & Sandoval-Hernandez, A. (2015). Desigualdad económica y conocimiento cívico. Chile en comparación internacional. En : Castillo, J. & Cox, C. Aprendizaje de la Ciudadanía: Contextos, experiencias y resultados. Ediciones UC, Santiago. Pp. 487- 524

- Cox, C.; Bascopé, M.; Castillo, J.C.; Miranda, D. & Bonhomme, M. (2015). Capítulo de libro: Educación Ciudadana en América Latina: Prioridades en los Currículos Escolares. En: Castillo, J. & Cox, C. Aprendizaje de la Ciudadanía: Contextos, experiencias y resultados. Ediciones UC, Santiago. Pp. 321-371

- Castillo, J.C.; Miranda, D. & Bonhomme, M. (2015). Capítulo de libro: Desigualdad Social y cambios en las expectativas de participación política de los estudiantes en Chile. En: Castillo, J. & Cox, C. Aprendizaje de la Ciudadanía: Contextos, experiencias y resultados. Ediciones UC, Santiago. Pp. 459-486

- Cox, C., Bascopé, M., Castillo, J., Bonhomme, M., Miranda, D. (2014) Educación Ciudadana en América Latina: Prioridades de los Currículos. Working Papers on Curriculum Issues, UNESCO International Bureau of Education (IBE) [link]("documentos/papers/cox et al 2015 Unesco IBE educacion ciudadana LA.pdf")

- Castillo, J. & Olivos, F. (2014) Redistribución e impuestos: Un análisis desde la opinión pública. En Atria, J. Tributación en Sociedad: Impuestos y Redistribución en el Chile del Siglo XXI (143-166). Santiago: Uqbar. [link]("documentos/papers/castillo & olivos 2014 redistribucion en impuestos.pdf")
-
- Castillo, Miranda & Carrasco (2011). La percepción de desigual de la desigualdad (The unequal perception of inequality). Technical report IT1101, Measurement Center Mide-UC. Santiago: P. Universidad Católica de Chile.

- Castillo, J. (2011). The legitimacy of economic inequality: An empirical approach to the case of Chile. Boca R.: Dissertation.com. ISBN 1-59942-376-6 [link](https://books.google.cl/books?id=3nLo_ha-sTgC&printsec=frontcover&hl=es#v=onepage&q&f=false).

- Castillo & Carrasco (2010). Sobre la estabilidad del autoritarismo: Un caso de medición de invarianza longitudinal. (On the stability of authoritarianism: A case of measurement invariance). Technical report IT1008, Measurement Center Mide-UC. Santiago: P. Universidad Católica de Chile.

- Castillo, J. (2008) Factorial survey: Dimensions of Just Rewards. International Social Justice Project - Working Paper N°165. Berlin: Humboldt University.

- Castillo, J., Gerlitz, J., & Schrenker, M. (2008). Perception and Legitimacy of Income Inequality in International Comparison. International Social Justice Project - Working Paper N°168. Berlin: Humboldt University.

- Castillo, J., Mühleck, K., & Wegener, B. (2008). The Empirical Approach to the Study of Social Justice: A Research Agenda for Latin America. Observatory on Inequality in Latin America – Working Paper N°24. Miami: University of Miami.

- Schneider, S., & Castillo, J. (2007). Internal and External Attributions of Poverty - Germany 1991/ 2006. International Social Justice Project - Working Paper N°132, Berlin: Humboldt University.

- Castillo, J., & Schneider, S. (2007). Internal and External Attributions of Poverty and Wealth. International Social Justice Project - Working Paper N°131, Berlin: Humboldt University.

- Castillo, J. (2007) Legitimation and Justice Ideologies in contexts of extreme economic inequality. International Social Justice Project - Working Paper N°125, Berlin: Humboldt University.

- Castillo, J., & Asun, D. (2002). Creencias en la Justicia en el Mundo: Un Estudio Preliminar en Relación a Actitudes de Intolerancia y Discriminación. In D. Paez (Ed.), Psicología Social. Buenos Aires: Prentice Hall.

</details>

<br/>

## Conferences

[CEPAL 2019 Taller interno Cohesión Social](documents/CEPAL2019/pres02.html)

[Desigualdad, Justicia y Redistribución, Foro FACSO 2019](documents/foroFACSOnov2019/castillo2019forofacso.html)

[Colaboración y Ciencia Abierta (Seminario COES _Abrir la Academia_). 10 de Septiembre 2019, FEN Universidad de Chile.](documents/abrir-la-academia/presentacion.html)

Desigualdad Económica, Percepción de Meritocracia y Preferencias Redistributivas (Congreso Chileno de Sociología - Diciembre 2018) [(*link to presentation*)](https://juancarloscastillo.github.io/jc-castillo/documents/presentacion-final/present-panel-alas2018.html#1)

Meritocracia y redistribución en una sociedad desigual (Conferencia COES - Noviembre 2018) [(*link to presentation*)](https://juancarloscastillo.github.io/jc-castillo/documents/coes2018/castillo2018meritocracyCOES.html#1)

Open academic writing: An Atom-based workflow for social scientists (SocArxiv 2018 Conference - Maryland)[(*link to presentation*)](https://juancarloscastillo.github.io/jc-castillo/documents/atomworkflow/Xiringito_press.html#1)

Castillo,JC (2018) Perceptions and preferences about meritocracy in international comparison. Congress of the International Sociological Association - ISA (July 15-21). Toronto, Metro Toronto Convention Center [(to presentation)](documents/ISA2018presentation/castillo2018meritocracyISA.html).

Castillo, JC. & Jaime-Castillo, A. (2018) Reciprocity and Distributive Justice. Joint session organized for the Research Committee 42 (Social Psychology)  and 45 (Rational Choice) at the Congress of the International Sociological Association - ISA (July 15-21). Toronto, Metro Toronto Convention Center.

Castillo, JC. (2017) Percepciones y legitimación de la desigualdad: Mérito e Instituciones. Panel Congreso Latinoamericano de Sociología (Diciembre 2-7). Montevideo, Universidad de la República.

Castillo, JC. (2017) Meritocracia y preferencias redistributivas. Panel Conferencia COES (Noviembre 8-9. Viña del Mar, Universidad Adolfo Ibañez.

Castillo, JC. (2017) Meritocratic beliefs and economic inequality. Colloquium of Macro Sociology (Julio 12). Berlin, Humboldt University.

Castillo, JC. & Miranda, D. (2017) Class and Status as Predictors of Inclusive Attitudes Towards Immigrants, Minorities and Gender. 7th IEA International Research Conference (IRC) (June 28-30). Prague, Charles University.

<details>
<summary> *See more...* </summary>

Castillo, JC. (2016) Origen y atribuciones de la pobreza y desigualdad social (origins and atributions of poverty and social inequality). Session organizer, COES-LSE Conference "Inequalities". (Nov. 3-5). Santiago, Chile.

Castillo, JC (2016) Desigualdad y meritocracia (inequality and meritocracy). Presentation at the conference cycle "Catedra Investigación Santiago" (Oct. 19). Santiago, Chile.

Castillo, JC (2016) Meritocracia y explicaciones de la pobreza: Medición y vinculaciones (meritocracy and poverty explanations: measurement and links). Session organizer, "Congreso Chileno de Sociología" (October 11-14). Talca, Chile.

Castillo, JC. & Frei, R. (2016) Clases de atribuciones de riqueza y pobreza (class attributions of poverty and wealth). Paper presented at the "Congreso Chileno de Sociología" (October 11-14). Talca, Chile.

Castillo, JC. (2016) Meritocracia y preferencias redistributivas (meritocracy and redistributive preferences). Research colloquium Institute of Sociology, Pontificia Universidad Católica de Chile (Oct. 4). Santiago, Chile.

Castillo, JC (2016) Economic Inequality, Distributive Preferences and Political Outcomes (I & II). Sessions organized for the Research Committee 42 (Social Psychology) at the Congress of the International Sociological Association - ISA (July 9-14). Vienna, Austria.

Castillo, JC (2016) Inequality, Distributive Preferences and Types of Participation in Latin America. Paper presented at the Congress of the International Sociological Association - ISA (July 9-14). Vienna, Austria.

Castillo, JC. & Miranda, D. (2015) Origen social, conocimiento cívico y participación en la escuela. CIEP - Congreso Internacional de Educación y Pobreza (January 08 - 10) Villarrica, Chile.

Miranda, D. & Castillo, JC.  (2015) Lo civil y lo civico: Hacia un modelo conceptual y de medición de ciudadanía escolar. CIEP - Congreso Internacional de Educación y Pobreza (January 08 - 10) Villarrica, Chile.

Castillo, JC., Olivos, F. & Azar. A. (2015) What is a just pension? A factorial survey approach. WAPOR (June 16-19) Buenos Aires, Argentina.

Castillo, J. (2014) Inequality, justice beliefs and political participation in Latin America. Paper presented at the Congress of the International Sociological Association - ISA (July 13-19). Yokohama, Japan.

Bargsted, M., Castillo, J. & Somma, M. (2014) Political trust in Latin America. Paper presented at the WAPOR Latin America Conference (18-20 June). Santiago de Chile.

Castillo, J. (2014) Economic inequality and Social Justice in Latin America. Poster presented at the Herrenhausen Konferenz: Re-thinking social inequality (May 12-14). Hannover, Germany.

Bargsted, M., Castillo, J. & Somma, M. (2014) Political trust in Latin America. Paper presented at the authors' workshop of the Handbook of Political Trust (May 15-18). Goethe Universität Frankfurt am Main, Germany.

Castillo, J., Tham, M. & Palacios, D. (2013) Desigualdad, justicia distributiva y participación política en Chile. Paper presented at the “Congreso de la Asociación Latinoamericana de Sociología – ALAS” (September 29 –October 4). Santiago de Chile.

Miranda, D., Castillo, J., Cox, C., Bascopé, M., & Bonhomme, J. (2013) Autoritarismo y Valores Democráticos en Estudiantes Latinoamericanos. Paper presented at the “Congreso de la Asociación Latinoamericana de Sociología – ALAS” (September 29 – October 4). Santiago de Chile.

Zmerli, S. & Castillo, J. (2013) Income inequality and social trust in Latin American societies. Paper presented at the “7th ECPR General Conference”, Panel: Dismantling Democracy: The Challenge of Inequality to Political Engagement. (September 4-7). Bordeaux.

Miranda, D., Castillo, J., Cox, C., Bascopé, M., & Bonhomme, J. (2013) Socioeconomic background and expected political participation at school: individual and contextual mechanisms. Paper presented at the summer school “Rising Inequalities and their impacts on Societies” (September 2-6). Levico, Italy.

Castillo, J., Miranda, D., Bonhomme, M., Cox, C. & Bascopé, M. (2013) Mitigating the participation gap from the school: The role of civic knowledge and classroom climate. Paper presented at the research colloquium of the Data Processing and Research Center, International Association for the Evaluation of the Educational Achievement (IEA). (August 7). Hamburg, Germany.

Miranda, D., Castillo, J., Cox, C.,  Bascopé, M., & Bonhomme, J.  (2013) Factors related to an open classroom climate and its impact on civic and expected political participation. Paper presented at the ”XV Comparative Education World Congress: New Times, New Voices” - WCCES (June 24-28). Buenos Aires, Argentina.

Castillo, J., Madero, I., Miranda, D. & Escobar, J. (2012) Education, equity and distributive beliefs: Evidence from the chilean case. Paper presented at the International Sociological Association - ISA Forum (August 1-4). Buenos Aires.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., & Escobar, J. (2012) Desigualdad económica y cambios en las expectativas de participación de estudiantes en Chile. Paper presented at the ”Congreso Interdisciplinario de Investigación en Educación” - CIIE (August 23-24). Santiago de Chile.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., & Escobar, J. (2012) Civic knowledge and political participation. Six Latin American countries in comparative perspectives. Paper presented at the International Sociological Association - ISA Forum (August 1-4). Buenos Aires.

Zmerli, S. & Castillo, J. (2012) Income inequality and political support: How objective and subjective inequality affect Latin Américan democracies. Paper presented at the Annual Scientific Meeting of the  International Society of Political Psychology – ISPP (July 5-9). Chicago.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., & Escobar, J. (2012) Social inequality and changes in students' expected political participation in Chile. Paper presented at the Annual Scientific Meeting of the  International Society of Political Psychology – ISPP (July 5-9). Chicago.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., Madero, I. & Escobar, J. (2012) Social origin and citizenship participation in Latin American schools. Paper presented at AERA Conference (April 13-17). Vancouver.

Castillo, J., Cox, C., Miranda, D., Bascopé, M., Madero, I. & Escobar, J. (2011) Actitudes hacia la democracia en estudiantes chilenos. Primer Congreso Nacional de Ciencias Sociales y Educación. Valparaíso: Universidad Católica de Valparaíso

Castillo, J., Salamovich, A. & Madero, I. (2011) Clivajes partidarios y preferencias distributivas. IV Congreso Nacional de Psicología. Santiago: Universidad de Chile.

Castillo, J., Salamovich, A. & Miranda, D. (2011) Partisan cleavages and distributive preferences: A cross sectional time comparison. Poster presented at the “Annual Scientific Meeting of the  International Society of Political Psychology – ISPP” (July 9-12). Istanbul: Bilgi University.

Castillo, J., Miranda, D. & Torres, P. (2011) Authoritarianism, Social Dominance & Trust in Public Institutions. Paper presented at the “Annual Scientific Meeting of the  International Society of Political Psychology – ISPP” (July 9-12). Istanbul: Bilgi University.

Castillo,J., Miranda, D. & Madero, I. (2011). Todos somos de clase media: Sobre el estatus social subjetivo en Chile. Paper presented at the “VI Congreso Nacional de Sociología – Pre ALAS 2011” (Apr. 13-15). Valparaíso: Universidad de Playa Ancha.

Castillo, J. & Miranda, D. (2010) Cambios en la relación entre religión e identidad política en Chile. (Changes in the relationship between religion and political identity in Chile). Presentation at the international seminar "Jóvenes, cultura y religión". Santiago: P. Universidad Católica de Chile.

Castillo, J. (2010)  Is inequality becoming just? Changes in public opinion about economic inequality in Chile. Paper presented at the "XXIX International Congress of the Latin American Studies Association" (Oct. 6-9). Toronto: Sheraton Conference Center.

Castillo, J. (2010) Higher salaries but stable inequality? A cross-sectional comparison of attitudes towards economic distribution. Paper presented at the "13th biennal conference of the International Society for Justice Research" (Aug. 21-24). Banff (Canada): The Banff Centre.

Castillo, J., Miranda, D. & Carrasco, D. (2010) Percepción de la desigualdad económica en Chile: Medición, determinantes y sesgos. (Perception of economic inequality in Chile: Measurement, determinants and biases). Presentation at the symposium "Tendencias emergentes de la (des) igualdad social: Desafíos para Chile y América Latina". Santiago: Universidad de Santiago.

Castillo, J. (2010). Cambios en la percepciones de la desigualdad económica en Chile (Changes in the perceptions of economic inequality in Chile). Presentation at the conference "La desigualdad: Legitimación y conflicto en las sociedades latinoamericanas". (July 21-24). Santiago: Universidad Alberto Hurtado.

Castillo, J. (2009) Herkunftsbedingte Disparitäten im Hochschulzugang in Chile und Deutschland (Desigualdades de origen social en el ingreso a la Universidad en Chile y en Alemania). Presentación en la conferencia “Herausforderungen der Globalisierung” (Nov. 20-21) Berlin: Iberoamerikanisches Institut.

Castillo, J. (2009). Perception and Legitimacy of Economic Inequality in Chile. Paper presentad at “5th ECPR General Conference” (Sept. 10-12). Potsdam: Potsdam University.

Castillo, J. (2009). What are Just Salaries for Different Occupations in Chile? Paper presentado en el “21st World Congress of Political Science – IPSA” (July 12-16). Santiago de Chile: Universidad de Chile.

Castillo, J. & Schneider, S., &. (2009). The Legitimacy kf Social Inequality in Comparative Perspective: Do People and Countries Differ in their Poverty Attributions? Paper presentado en el “21st World Congress of Political Science – IPSA” (July 12-16). Santiago de Chile: Universidad de Chile.

Schneider, S. & Castillo, J. (2009) Social Justice and Political Participation. Paper presentado (por el primer autor) en la “32nd Conference of the International Society of Political Psychology – ISPP” (July 14-17). Dublin: Trinity College.

Castillo, J. (2009). Consensus and Legitimacy of Earnings Inequality. Presentación en el  “International Social Justice Project Workshop” (May 6-10). Haifa: Haifa University, Israel.

Castillo, J. (2009). ¿Consenso o Conflicto acerca de la Distribución? La Legitimación de la Desigualdad Económica en Chile en Perspectiva Comparada. Paper presentado en la “2nd Latin American Conference of the World Association for Public Opinion Research” (April 22-24). Lima: Universidad Católica.

Castillo, J. (2008). Legitimación de la Desigualdad Económica en Chile. Presentación en la Universidad Academia de Humanismo Cristiano (December 10th), Santiago de Chile.

Castillo, J., Gerlitz, J., & Schrenker, M. (2008). Perception and Legitimacy of Income Inequality in International Comparison. Paper presentado en la “APSA Annual Conference” (Aug. 28-31). Boston: Conference Center

Castillo, J. (2008). On the Justice of Occupational Earnings in Chile: A Factorial Survey Analysis. Presentación en la “12th Conference of the International Society for Justice Research” (August 14-17). Adelaide: Flinders University.

Castillo, J., & Schneider, S. (2008). The Legitimacy of the Distributive System: A Comparison of Germany and Chile. Paper presentado en la “31st Conference of the International Society of Political Psychology – ISPP” (July 9-12). Paris: Sciences Po.

Castillo, J., Mühleck, K., & Wegener, B. (2008). The Empirical Approach to the Study of Social Justice: A Research Agenda for Latin America. Paper presentado en la conferencia "Intra- and inter- generational Transmission of Inequality" (Feb. 28-29). Mexico: Regional Bureau for Latin America and the Caribbean of United Nations Development Program (RBLAC-UNDP).

Castillo, J. (2007). Explanations of Poverty: A Comparison of Germany, the Czech Republic and Chile. Persentación en el “International Social Justice Project Workshop” (April 27-28). Budapest: Social Sciences Faculty, Eötvös Loránd University.

Castillo, J. (2007). Legitimation and Justice Ideologies in Contexts of Extreme Economic Inequalities. Paper presentado en la “30th Conference of the International Society of Political Psychology (July 4-7)”. Portland: Embassy Suites Hotel.

Castillo, J. (2007). Justice Ideologies and Attributions of Poverty in Comparative Perspective. Presentación en la conferencia "Law and Society in the 21st Century" (July 15-28). Berlin: Humboldt University.

Castillo, J. (2006). Justice Ideologies in Highly Unequal Contexts. The Case of Chile in Comparative Perspective. Poster presentado en la “11th  Conference of the International Society for Justice Research” (August 2-5). Berlin: Humboldt University.

</details>

<br/>

## Supervised thesis

<br/>

### *As first advisor*

<br/>

- Beck, G. (2019) Explorando la asociación entre redes de contacto ocupacionales y la justificación de la desigualdad social en Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Yañez, R. (2019) Construcción de juicios de justicia y emergencia de sentimientos de injusticia frente a la desigualdad social. Doctorado en Sociología, EHESS Paris (codirector).

- Iturra, J. (2018) Estatus social subjetivo y Percepción de meritocracia: El caso de Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Rojas, S. (2018) La dimensión subjetiva de la desigualdad de género en ingresos: Factores individuales asociados a evaluación de lo percibido y lo justo. Magíster en Sociología, P. Universidad Católica de Chile.

- Miranda, D. (2018) The civic and civil dimensions of youth participation. Doctorado en sociología, P. Universidad Católica de Chile.

- Plaza, A. (2018) Movilidad social y preferencias por la redistribución: Efectos individuales y contextuales. Magíster en Sociología, P. Universidad Católica de Chile.

- Franetovic, G. (2018) Desigualdad, desarrollo económico y preferencias redistributivas en América Latina. Magíster en Sociología, P. Universidad Católica de Chile.

- Muñoz, E. (2018) Evaluaciones de justicia distributiva sobre las pensiones de vejez en Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Castro, F. (2018) ¿Menos confianza, menos Estado? El impacto de la corrupción sobre las preferencias redistributivas. Magíster en Sociología, P. Universidad Católica de Chile.


<details>
<summary> *See more...* </summary>


- Sandoval, D. (2017) Merezco estar aquí: Un estudio multinivel sobre la relación entre meritocracia y educación. Magíster en Sociología, P. Universidad Católica de Chile.

- Montedónico, S. (2017) Contexto Polı́tico Institucional y Preferencias Redistributivas en América Latina. Magíster en Sociología, P. Universidad Católica de Chile.

- Acevedo, F. (2017) Compromiso Cívico Juvenil en Chile: una aproximación desde los recursos. Magíster en Sociología, P. Universidad Católica de Chile.

- Placencio, M. (2016) Legitimidad del Sistema Económico y Participación Ciudadana: Una aproximación a la relación entre percepciones individuales y actividad política en Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Viertel, F. (2016) Medición en ciudadanía: Equivalencia y propiedades psicométricas de una escala de percepción en estudiantes. Magíster en Medición, Escuela de Psicología, P. Universidad Católica de Chile.

- Santander, E. (2015) ¿Qué puede hacer la cultura de la escuela para aumentar la participación política de sus estudiantes? Magíster en Sociología, P. Universidad Católica de Chile.

- Torres, A. (2014) Aspectos subjetivos de la meritocracia y su relación con la percepción de desigualdad en Chile. Magíster en Psicología Social-Comunitaria, P. Universidad Católica de Chile.

</details>
<br/>

### *Evaluation committee*

<br/>

- Nuñez, R. (2017) Cambio cultural en Chile: un análisis sobre los valores posmaterialistas, la justificación a la homosexualidad y al aborto, desde 1990 al 2011. Magíster en Sociología, P. Universidad Católica de Chile.

- Lozier. D. (2017) Comportamiento ambiental en Chile: Factores situacionales y efecto contexto en el nivel de adopción de conductas ecológicas en la región Metropolitana. Magíster en Sociología, P. Universidad Católica de Chile.

- Velasquez, D. (2017) Acción policial en las huelgas en Chile 2010-2015: La disputa por el orden productivo. Magíster en Sociología, P. Universidad Católica de Chile.

- Fromm, G. (2017) A structural model of educational leadership and contexts influence over teachers’ efficacy beliefs. Doctorado en Educación, Pontificia Universidad Católica de Chile.

<details>
<summary> *See more...* </summary>

- Villarroel, N. (2016) Stability and change in political right-wing groups in Chile: understanding the shift among right wingers to the center. Magíster en Psicología Social, Pontificia Universidad Católica de Chile.

- Meza, F. (2016) Confianza política y conocimiento cívico en adolescentes chilenos de octavo básico. Magíster en Sociología, P. Universidad Católica de Chile.

- Espinoza, A. (2015) La productividad y la colaboración en el reconocimiento cientı́fico de los astrónomos de Chile. Magíster en Sociología, P. Universidad Católica de Chile.

- Valenzuela, D. (2015) Coexistencia entre prácticas de cuidado y de explotación. Magíster en Sociología, P. Universidad Católica de Chile.

- Trebilcok, M. (2015) Hijos, amigos y mineros: Vínculos de cohesión social en el trabajo. Doctorado en Sociología, P. Universidad Católica de Chile.

- Ibañez, S. (2015) La legitimación de las desigualdades Salariales. Doctorado en Sociología, Universidad Alberto Hurtado.

- Ortúzar, L. (2013) Creencias de Mundo Justo en Jóvenes Chilenos según status social. Magíster en Psicología Social, P. Universidad Católica de Chile.

- Gómez, K. (2013) Microfinanzas en Chile: Su impacto en el Capital Social, Empoderamiento y Equidad de Género, Magíster en Psicología Social, P. Universidad Católica de Chile.

</details>
