---
title: "Taller Markdown y herramientas de escritura abierta"
output:
    html_document:
        theme: readable
        css: style.css
#        toc: TRUE
        #toc_float: TRUE
        includes:
          before_body: header.html
---
<div class="mycontent">

# Markdown y herramientas de escritura abierta ([bit.ly/markdown-herramientas](https://juancarloscastillo.github.io/jc-castillo/documents/talleres-cursos/markdown-mexico/markdown-herramientas.html))

**Edición, citas, versionamiento y publicación**

Agosto 2021 - Universidad Iberoamericana de México

Juan Carlos Castillo, Departamento de Sociología, Universidad de Chile

[jc-castillo.com](https://juancarloscastillo.github.io)


### Sesiones

<font size="3">

|              	| Sesión                                    	| Práctico                          	|
|-------------------	|:-------------------------------------------	|:-----------------------------------	|
| Lunes 16     	| [Introducción a escritura en texto simple](slides/01-textosimple/01_textosimple.html)  	| - [Editor.md](https://pandao.github.io/editor.md/en.html) <br> - [Tutorial Markdown online](https://www.markdowntutorial.com/es/) 	|
| Miércoles 18 	| [Escribiendo Markdown en ATOM](slides/02-atom/02_atom.html)                 	| - [Instalación y funcionamiento ATOM](https://atom.io/) <br> - Librerias ATOM-Markdown           	|
| Viernes 20   	| [Citas en texto plano ](slides/03-bibtex/03_bibtex.html)                     	| Zotero, Bibtex & Betterbibtex     	|
| Lunes 23     	| [Versionamiento y repos con Git & Github](slides/04-git/04_git.html)    	| Repositorios Github               	|
| Miércoles 25 	| [Renderización y Publicación](slides/05-pub/05_pub.html)              	| Github pages                      	|

</font>


## Links

- Instalación y documentación ATOM: [https://atom.io/]()


## Comentarios & preguntas

- [hypotes.is](https://web.hypothes.is/)

<br><br><br>
</div>
