---
title: "Modelos Multinivel"
output:
    html_document:
        theme: readable
        css: style.css
        toc: TRUE
        #toc_float: TRUE
        includes:
          before_body: header.html
---
<div class="mycontent">
# DIPLOMADO ANALISIS MULTIVARIABLE
2do SEM 2019

(link abreviado de este sitio: [bit.ly/dip-multinivel](http://bit.ly/dip-multinivel) )

Profesor: Juan Carlos Castillo, Departamento de Sociología, Universidad de Chile
[jc-castillo.com](https://juancarloscastillo.github.io)


# Descripción

Gran parte de la investigación sociológica hace referencia al contexto en que las personas viven y se desenvuelven, como por ejemplo lugares de trabajo, salas de clases, barrios, países. Sin embargo, modelos tradicionales como ANOVA y regresión poseen limitaciones a la hora de integrar datos en distintos niveles (individual y contextual), así como también la interacción entre ambos (por ejemplo, la relación entre nivel de vulnerabilidad de escuelas, capital cultural de los padres y rendimiento académico de estudiantes). El presente curso aborda el análisis simultáneo de datos en distintos niveles mediante modelamiento multinivel. Comienza con una problematización de la integración del contexto en el análisis sociológico de datos, para luego describir las principales características y usos de modelos multinivel.

<br/>
<br/>

# Sesiones

<font size="5">


|             	|    	|                                                            	|            	|
|-----------------	|--------	|------------------------------------------------------------	|----------------	|
| Septiembre  	| 25 	| [Introducción y bases ](1mlmintro.html)                    	|            	|
|             	| 26 	| [Estimando en distintos niveles](2mlm2niveles.html)                         	| [Práctica A](https://multinivel.netlify.com/practicas/a_introreg/a_introreg.html) 	|
| Octubre     	| 2  	|[ Correlación intra-clase y predictores en distintos niveles](3mlmICC.html) 	| [Práctica B](https://multinivel.netlify.com/practicas/b_iccranef/b_icc-ranef.html) 	|
|             	| 3  	| [Efectos aleatorios](4mlmranef.html)                                         	| [Práctica C](https://multinivel.netlify.com/practicas/c_ranef.html) 	|
|             	| 9  	| [Ajuste y reporte](5fitrep.html)                                  	| [Práctica D](d_ajuste-reporte.html) 	|
|             	| 10 	| [Interacción entre niveles](6inter_logit.html)                     	| [Práctica E](e_interaccion.html) 	|

</font>


# Lecturas

- Bibliogafía básica

  - [Finch et al (2014) Multilevel modeling using R](bibliografia/finch et al 2014 multilevel modeling using R.pdf)

  - [Aguinis et al (2013) Best-Practice Recommendations for Estimating Cross-Level Interaction Effects Using Multilevel Modeling](https://multinivel.netlify.com/readings/aguinis2013crosslevel.pdf)

# Links

- Ejemplos artículos investigación:
  - [Origen familiar, uso del tiempo y de las tecnologías de la información](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/1037/1385)
  - [Actitudes cívicas y dimensiones de la ciudadanía democrática en Europa](http://www.reis.cis.es/REIS/PDF/REIS_125_021231144957544.pdf)


# Evaluación

El trabajo final del curso consiste en una aplicación práctica de la estimación de modelos multinivel a una problemática definida por los alumnos y para la cual se cuenta con datos secundarios. Se puede realizar en grupos de máximo 3 integrantes.

El informe final debe tener formato de artículo o reporte breve de investigación, con las siguientes secciones y número de palabras sugeridas (entre 3.500-4500 palabras en total):

Tı́tulo

Abstract: problema, pregunta, objetivo, datos (y N), resultado principal.

1. Introducción: definición de la problemática a abordar, su relevancia y enmarque dentro de los contenidos del curso. Es importante hacer referencia a la relevancia de variables contextuales y posible interacción con variables individuales, ası́ como también a la relevancia sociológica del estudio. Como es un artı́culo breve, la introducción incluye también antecedentes conceptuales y de estudios anteriores (1000 palabras)

2. Objetivos e hipótesis (incluir hipótesis diferenciadas por niveles) (250 palabras)

3. Datos, variables y métodos: datos a utilizar (N general y aproximado por unidad de nivel 2, descripción general de los datos, año de aplicación) variables, estadı́sticos descriptivos univariados, descripción de los modelos a estimar (500 palabras).

4. Resultados: se recomienda la menor cantidad de tablas con resumen de modelos estimados, gráficos, descripción e interpretación de los principales hallazgos en relación a las preguntas de investigación (1500-2000 palabras)

5. Resumen y conclusiones: principales hallazgos, respuesta a preguntas, ventajas de la estimación multinivel para abordar la problemática, limitaciones, recomendaciones para futuras investigaciones (250 - 500 palabras).

6. Bibliografı́a

**Formato**: Idealmente en formato html/(R)Markdown; en caso de formato papel, tamaño carta, letra times new roman o LM Roman 12, espaciado 1,5, margenes de 2 cm, número de página. En todos los casos se debe adjuntar el código de análisis; si en el informe de avance se utiliza Rmarkdown - html se puede incluir el código (”chunks”) en el informe. Lo importante, sobre todo en la primera entrega, es preocuparse por el contenido más que el formato.


<br><br><br>
</div>
